update docker

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,13 +1,19 @@
-FROM nvidia/cuda:11.7.0-cudnn8-devel-ubuntu20.04
+# Dockerfile for AlgoPerf environment.
+# To build Docker image with only Jax GPU installed:
+# docker build -t <image_name> --build-arg framework=jax
+# To build Docker image with Pytorch GPU installed:
+# docker build -t <image_name> --build-arg framework=pytorch
 
-# ARG GIT_URL=https://github.com/mlcommons/algorithmic-efficiency.git
-ARG GIT_URL=https://github.com/priyakasimbeg/algorithmic-efficiency.git
+# To build Docker image
+FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
 
 # Installing machine packages
 RUN echo "Setting up machine"
 RUN apt-get update
 RUN apt-get install -y curl tar
 RUN apt-get install -y git python3 pip wget
+RUN apt-get install libtcmalloc-minimal4
+RUN export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
 
 # Install GCP tools
 RUN echo "Setting up gsutil"
@@ -22,13 +28,38 @@ RUN mkdir -p experiment_runs/
 
 # Install Algorithmic efficiency repo
 RUN echo "Setting up algorithmic_efficiency repo"
-RUN git clone $GIT_URL && cd algorithmic-efficiency && git fetch origin && git checkout timing_test_2
+ARG branch="main"
+ARG framework="both"
+ARG git_url=https://github.com/mlcommons/algorithmic-efficiency.git
+RUN git clone $git_url && cd algorithmic-efficiency 
+RUN cd algorithmic-efficiency && git checkout $branch
 
 RUN cd algorithmic-efficiency && pip install -e '.[full]'
+
+RUN if [ "$framework" = "jax" ] ; then \
+        echo "Installing Jax GPU" \
+        && cd algorithmic-efficiency \
+        && pip install -e '.[jax_gpu]' -f 'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html' \
+        && pip install -e '.[pytorch_cpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'; \
+    elif [ "$framework" = "pytorch" ] ; then \
+        echo "Installing Pytorch GPU" \
+        && cd algorithmic-efficiency \
+        && pip install -e '.[jax_cpu]' \
+        && pip install -e '.[pytorch_gpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'; \
+    elif [ "$framework" = "both" ] ; then \
+        echo "Installing Jax GPU and Pytorch GPU" \
+        && cd algorithmic-efficiency \
+        && pip install -e '.[jax_gpu]' -f 'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html' \
+        && pip install -e '.[pytorch_gpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'; \
+    else \
+        echo "Invalid build-arg $framework: framework should be either jax, pytorch or both." >&2 \
+        && exit 1 ; \
+    fi
+
 RUN cd algorithmic-efficiency && pip install -e '.[wandb]'
 
-RUN cd algorithmic-efficiency && pip install -e '.[jax_gpu]' -f 'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html'
-RUN cd algorithmic-efficiency && pip install -e '.[pytorch_gpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'
+RUN cd algorithmic-efficiency && git fetch origin 
+RUN cd algorithmic-efficiency && git pull
 
 # Todo: remove this, this is temporary for developing
 COPY scripts/startup.sh /algorithmic-efficiency/docker/scripts/startup.sh
